---
abstract: 'All regional Acme::CPANAuthors modules at once'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-CPANAuthors-Regional
requires:
  Acme::CPANAuthors: '0'
  Acme::CPANAuthors::Australian: '0'
  Acme::CPANAuthors::Austrian: '0'
  Acme::CPANAuthors::Belarusian: '0'
  Acme::CPANAuthors::Brazilian: '0'
  Acme::CPANAuthors::British: '0'
  Acme::CPANAuthors::Canadian: '0'
  Acme::CPANAuthors::Catalonian: '0'
  Acme::CPANAuthors::Chinese: '0'
  Acme::CPANAuthors::Czech: '0'
  Acme::CPANAuthors::Danish: '0'
  Acme::CPANAuthors::Dutch: '0'
  Acme::CPANAuthors::EU: '0'
  Acme::CPANAuthors::European: '0'
  Acme::CPANAuthors::French: '0'
  Acme::CPANAuthors::German: '0'
  Acme::CPANAuthors::Icelandic: '0'
  Acme::CPANAuthors::India: '0'
  Acme::CPANAuthors::Indonesian: '0'
  Acme::CPANAuthors::Israeli: '0'
  Acme::CPANAuthors::Japanese: '0'
  Acme::CPANAuthors::Korean: '0'
  Acme::CPANAuthors::Norwegian: '0'
  Acme::CPANAuthors::Polish: '0'
  Acme::CPANAuthors::Portuguese: '0'
  Acme::CPANAuthors::Russian: '0'
  Acme::CPANAuthors::Spanish: '0'
  Acme::CPANAuthors::Swedish: '0'
  Acme::CPANAuthors::Taiwanese: '0'
  Acme::CPANAuthors::Turkish: '0'
  Acme::CPANAuthors::Ukrainian: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Task-CPANAuthors-Regional
  repository: http://github.com/book/Task-CPANAuthors-Regional.git
version: '1.000'
